<?php
/**
 * Implements hook_menu()
 */
function custom_menu() {
    $items ['admin/config/test'] = array(
        'title' => 'Custom module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('custom_form'),
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
    );

    return $items;
}

function custom_form($form, &$form_state) {
    $form = array();
    $form['title'] = array(
        '#type' => 'textfield',
        '#title' => 'Title node',
        '#size' => 50,
        '#maxlength' => 50,
        '#required' => TRUE,
    );
    $form['description'] = array(
        '#type' => 'textarea',
        '#title' => 'Description',
    );
    $form['body'] = array(
        '#type' => 'textarea',
        '#title' => 'Body content',
    );
    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
    );
    return $form;
}

function custom_form_submit($form, &$form_state) {
    dsm($form_state);
    $c_id = db_insert('custom')
        ->fields(array(
                'title' =>  $form_state['values']['title'],
                'description' =>  $form_state['values']['description'],
                'body' =>  $form_state['values']['body'],
            )
        )
        ->execute();
    drupal_set_message(t('Done !!!'));
}

function custom_form_validate($form, &$form_state) {
    return True;
}

