<?php
/**
 * Implements hook_views_api().
 */
function gravity_admin_views_api() {
    return array(
        'api' => 3,
    );
}

/**
 * Implements hook_menu()
 */
function gravity_admin_menu() {
      $items ['administrator'] = array(
        'title' => 'Gravity',
        'page callback' => 'gravity_admin_theme',
        'access arguments' => array('access gravity admin'),
      );

    $items ['administrator/config'] = array(
        'title' => 'Configuration',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('gravity_admin_config_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'gravity_admin.admin.inc',
    );

  return $items;
}

/**
 * Overwrite theme administrator
 */
function gravity_admin_theme() {
  return array(
    'page--administrator' =>  array(
      'template' => 'theme/page--administrator',
      'render element' => 'page'
    ),
  );
}
function gravity_admin_preprocess_page(&$variables){
  if ( arg(0) == 'administrator' ) {
    $variables['theme_hook_suggestions'][] = 'page--administrator';
  }
}
/**
 * Implements hook_system_info_alter()
 * Adds a new "gravity_menu" region to the current theme
 */
function gravity_admin_system_info_alter(&$info, $file) {
  global $theme;
  // If non-default theme configuration has been selected, set the custom theme.
  $custom_theme = isset ($theme) ? $theme : variable_get('theme_default', 'bartik');

  if ($file->name == $custom_theme){
    $info['regions'] = array_merge($info['regions'],  array('gravity_menu' => t('gravity_menu')));
    $info['regions'] = array_merge($info['regions'],  array('gravity_content' => t('gravity_content')));
  }
}
///**
// * Implements hook_views_pre_render().
// * Add content
// */
//function gravity_admin_views_pre_render(&$view, &$display_id, &$args) {
//    // Scramble the order of the rows shown on this result page.
//    // Note that this could be done earlier, but not later in the view execution
//    // process.
//    //dsm($display_id);
//    if ($view->name == "gravity_views_node") {
//        // dsm($view);
//
//        global $base_url;
//        $type = $_GET["type"];
//        $path = $base_url . "/" . arg(0) . "/" . arg(1) . "#overlay=/node/add/" .$type;
//        $alias = drupal_get_path_alias($path);
//        $header_content = '<a href="'.$alias.'">Add content</a>';
//
//        $header_options = array(
//            'label' => t('Header text'), // Administrative label. Not really needed here.
//            'content' => $header_content, // Content of header text.
//            'format' => 'filtered_html', // Format of header text.
//            'empty' => 1, // Show even when there are no results. Set to zero otherwise.
//        );
//        $view->add_item('default', 'header', 'views', 'area', $header_options);
//    }
//}
