<?php
/**
 * Implements hook_init()
 * Create menu name "Gravity admin"
 */
function gravity_admin_init(){
    $menu = array(
        'menu_name' => 'gravity_admin', // Drupal menu machine name
        'title' => 'Gravity admin', // Drupal menu display name
        'description' => 'Gravity admin', // Optional menu description
    );
    menu_save($menu);
}

/**
 * Implements hook_menu()
 */
function gravity_admin_menu() {
    $items ['administrator'] = array(
        'title' => 'Gravity',
        'page callback' => 'gravity_admin',
        'access arguments' => array('access gravity admin'),
    );

    return $items;
}

function gravity_admin() {
    return t('Create themes');
}


